### ISSUE TITLE
How to set up a ws endpoint server

### ISSUE THREAD

**Issue by shtse8** [DxCx/graphql-rxjs-websocket-example#1]
https://github.com/DxCx/graphql-rxjs-websocket-example/blob/master/src/main.js#L46

I don't understand as I am using https as my endpoint server. Is it really possible to setup a wss endpoint server? I have tried but no luck.

```
TypeError: Failed to fetch
    at graphQLHttpFetcher (https://api.domain.com/ui/ws?query=query%20%7B%0A%20%20simpleInt%0A%7D:71:18)
    at https://unpkg.com/graphiql-subscriptions-fetcher@0.0.2/browser/client.js:8749:20
    at t.value (https://unpkg.com/graphiql@0.11.2/graphiql.min.js:1:45916)
    at t.value (https://unpkg.com/graphiql@0.11.2/graphiql.min.js:1:39252)
    at e.notifyAll (https://unpkg.com/react-dom@15.6.1/dist/react-dom.min.js:12:7904)
    at r.close (https://unpkg.com/react-dom@15.6.1/dist/react-dom.min.js:14:18388)
    at r.closeAll (https://unpkg.com/react-dom@15.6.1/dist/react-dom.min.js:15:9758)
    at r.perform (https://unpkg.com/react-dom@15.6.1/dist/react-dom.min.js:15:9253)
    at s (https://unpkg.com/react-dom@15.6.1/dist/react-dom.min.js:14:11165)
    at r.perform (https://unpkg.com/react-dom@15.6.1/dist/react-dom.min.js:15:9170)
```

```
Fetch API cannot load wss://api.domain.com/subscriptions?. URL scheme must be "http" or "https" for CORS request.
```

**Comment by DxCx** [comment]
thanks @shtse8 i've merged your PR for fixing this..
now we will need to wait for a new graphiql version..

**Comment by shtse8** [comment]
@DxCx You are welcome. thanks for your contribution on reactive directive on graphql. It makes graphql more perfect. I have spent lots of time to study on codes and every word in github. It's amazing and I believe this is the best I have ever seem.
